const { Schema, model } = require('mongoose')
const Passes = model('Passes', new Schema({
    wc_line_id: String,
    wc_line_name: String,
    wc_line_product_id: String,
    wc_line_variation_id: String,
    wc_line_quantity: Number,
    wc_line_tax_class: String,
    wc_line_subtotal: Number,
    wc_line_total_tax: Number,
    wc_friday_activity: String,
    wc_shirt_size: String,
    wc_pass_photo_upload: String,
    wc_pass_holder_legal_first: String,
    wc_pass_holder_legal_last: String,
    wc_pass_holder_name_badge: String,
    wc_pass_holder_email: String,
    wc_line_sku: String,
    wc_order_id: String,
    wc_order_number: String,
    wc_order_status: String,
    wc_order_date_created: String,
    wc_order_date_modified: String,
    wc_order_discount_total: Number,
    wc_order_customer_id: String,
    wc_order_billing_first_name: String,
    wc_order_billing_last_name: String,
    wc_order_billing_address_1: String,
    wc_order_billing_address_2: String,
    wc_order_billing_city: String,
    wc_order_billing_state: String,
    wc_order_billing_country: String,
    wc_order_billing_zip: String,
    wc_order_billing_email: String,
    wc_order_phone: String,
    userId: { type: Schema.Types.ObjectId, ref: 'User' }
}))
module.exports = Passes 